{
 "title": "K1S Traefik Dashboard",
 "description": "K1S Traefik Dashboard",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service)" },
   { "name": "code", "query": "label_values(code)" }
  ]
 },
 "panels": [
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests by Service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (service) * 100",
     "legendFormat": "{{`{{ service }}`}}"
    }
   ]
  },
  {
   "title": "Requests by Entrypoint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total[5m])) by(entrypoint) * 100",
     "legendFormat": "{{`{{ entrypoint }}`}}"
    }
   ]
  },
  {
   "title": "Status Codes 2xx and 3xx Over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"^[2|3].*$\"}[5m]) ) by (method,code) *100",
     "legendFormat": "{{`{{ method }}`}} {{`{{ code }}`}}"
    }
   ]
  },
  {
   "title": "Status Codes 4xx and 5xx Over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"^[4|5].*$\"}[5m])) by (method,code) * 100",
     "legendFormat": "{{`{{method}}`}} {{`{{code}}`}}"
    },
    { "expr": "avg_over_time" }
   ]
  },
  { "title": "Services stats ($service)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Average Response Time Over 5min ($service)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(traefik_service_request_duration_seconds_sum{service=~\"$service\"}[5m])) by (service)",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  },
  {
   "title": "Total Requests Over 5min ($service)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(traefik_service_requests_total{service=~\"$service\"}[5m])) by(service)) * 100",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  },
  {
   "title": "Open Connections ($service)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{service=~\"$service\"}) by(service)",
     "legendFormat": "{{`{{service}}`}}"
    }
   ]
  }
 ]
}